### ISSUE TITLE
Algolia search results are returned twice

### ISSUE THREAD

**Issue by VladimirAlexiev** [OpenRefine/openrefine.org#135]
Now that OpenRefine/OpenRefine#5127 is fixed, I can search eg for "jython".
But every hit is returned twice:
![image](https://user-images.githubusercontent.com/536250/185400268-0daef0e3-b501-4881-bf7d-2be9a76dc8f7.png)

and the second match goes to an invalid (incomplete) URL: `https://technical-reference/writing-extensions#server-side-scripting-languages`

**Comment by wetneb** [comment]
It's working well now, after getting new Algolia credentials.
