### ISSUE TITLE
Fix 2 deficiencies in Documentation

### ISSUE THREAD

**Issue by alexkreidler** [OpenRefine/openrefine.org#148]
There are two features which as a new user I didn't really understand because they weren't on the "Documentation For Users" page.

1. Row mode vs Record mode. I finally figured it out thanks to [this article](http://kb.refinepro.com/2012/03/difference-between-record-and-row.html)
2. The difference between `null` and the empty string (`""`) -- I still don't understand this. After reading as much as I could stomach of OpenRefine/OpenRefine#820, OpenRefine/OpenRefine#1544, OpenRefine/OpenRefine#1571, I still really don't understand the fundamental difference in how they are represented and how they change the functionality of OpenRefine (e.g. during export). I have also found out that it seems easy enough to convert from `null --> ""` with the `coalesce()` function, but I don't know if it's possible to go from `"" --> null` or if I would ever even want to do so.

Thanks so much for an awesome tool! I have loved most of it so far and am super excited for its future!

I hope that someone can add a simple explanation of these two details to the Documentation For Users page, possibly in their own sections.

**Comment by ostephens** [comment]
The documentation has been completely overhauled since this issue was raised:

- null is documented at https://openrefine.org/docs/manual/exploring#data-types
- records vs rows is documented at https://openrefine.org/docs/manual/exploring#rows-vs-records

I think the new documentation addresses this issue
