### ISSUE TITLE
Update MacOS installation guidelines in OpenRefine's manual

### ISSUE THREAD

**Issue by trnstlntk** [OpenRefine/openrefine.org#149]
Now that OpenRefine/OpenRefine#2191 has been fixed and our MacOS installation procedure works fine, we can update our docs and remove the circumvention instructions for Mac users there (under https://docs.openrefine.org/manual/installing#install-or-upgrade-openrefine)

**Comment by amyra98** [comment]
Can you please assign me this issue @trnstlntk @jmsdncn @tfmorris @wetneb

**Comment by amyra98** [comment]
Just to be sure @trnstlntk @wetneb It used to display these warnings when we opened Openrefine on MacOS, but as of now it doesn't unless it's an outdated version, therefore I'll just remove this caution part as show in screenshot
![Installing OpenRefine _ OpenRefine - Google Chrome 16-03-2023 12_13_17](https://user-images.githubusercontent.com/75852935/225538028-75afc6bf-7751-4dc8-9a92-ba7f8eb2d433.png)
. And I don't need to say anything else.

**Comment by wetneb** [comment]
That sounds good to me @amyra98.

**Comment by amyra98** [comment]
I have done the corresponding PR at https://github.com/OpenRefine/openrefine.org/pull/206 but as its on other repository how should I link this issue to that?? @wetneb

**Comment by wetneb** [comment]
The issue and PR belong to the same repository so there should not be any problem with that. (By the way, PRs can actually close issues in different repositories as long as they are in the same organization)

**Comment by amyra98** [comment]
okay thanks for the info

**Comment by wetneb** [comment]
Closed by #206.
