### ISSUE TITLE
Add a link to contributing from the Community page on the website

### ISSUE THREAD

**Issue by thadguidry** [OpenRefine/openrefine.org#153]
I noticed we have this phrase
> * getting involved in the development of the tool;

which could probably point to an appropriate entry for contributing guide page or development (tech docs or some such?) or the forum Development category now? dunno.

**Comment by BhaswatiRoy** [comment]
Hello I would like to work on this issue
It would be great if it could be assigned to me
Thanks

**Comment by thadguidry** [comment]
@BhaswatiRoy First, we have to decide where to link to.  Do you have an opinion where it should link to?

**Comment by BhaswatiRoy** [comment]
![image](https://user-images.githubusercontent.com/78029145/211742335-20a526b6-e684-40f8-aec6-72ddc0d9cacd.png)
just like the 1st and 3rd text we can make the entire 2nd text a hyperlink to contributing page or contributing.md file

**Comment by wetneb** [comment]
Thanks for volunteering @BhaswatiRoy, looking forward to reviewing your pull request!

**Comment by BhaswatiRoy** [comment]
Hello @wetneb 
thanks for assigning
I have submitted the pr. Do let me know if I have to make any changes!
