### ISSUE TITLE
Links from search currently broken

### ISSUE THREAD

**Issue by ostephens** [OpenRefine/openrefine.org#155]
Search for a term such as "Reconciling"
Results include two types of broken links. For example:

- https://openrefine.org/manual/reconciling -> should be https://openrefine.org/docs/manual/reconciling
- https://manual/reconciling -> should not be there!

**Comment by wetneb** [comment]
That's really bad, so I have disabled search while we wait for new Algolia credentials.

**Comment by wetneb** [comment]
It looks like new Algolia credentials are on the way to the advisory committee, so we should soon be able to enable this back.

**Comment by wetneb** [comment]
This is solved
