### ISSUE TITLE
Search currently searches documentation only

### ISSUE THREAD

**Issue by ostephens** [OpenRefine/openrefine.org#156]
Should the search be extended to search the whole website?

**Comment by wetneb** [comment]
It should! I am hopeful that this just works out of the box as soon as Algolia starts crawling the new website. If that does not happen we should just register for new Algolia credentials to reindex it from scratch.

**Comment by thadguidry** [comment]
Verified that all paths are indexed by Algolia search.  And Level hierarchies are also indexed and maintained and shown in search dialog.  Closing.

![image](https://github.com/user-attachments/assets/01b41bd8-e769-47ab-be84-d5295c24f54e)
