### ISSUE TITLE
Improve blog navigation

### ISSUE THREAD

**Issue by magdmartin** [OpenRefine/openrefine.org#168]
Following the new website release #126 it is hard to locate older blog posts and because of #157 scrolling through pages is not user-friendly. 

As a work-around, I listed all previous [blog articles here](https://forum.openrefine.org/t/openrefine-blog-archive/276). But a list auto-generated on the website directly will be much nicer.

**Comment by wetneb** [comment]
We can configure the number of pages linked in the "Recent posts" sidebar, potentially showing all of them:
https://docusaurus.io/docs/blog#blog-sidebar

**Comment by Sanga-Pal** [comment]
Hi! I would like to work on this issue, can you elaborate a little about what is the need exactly..

**Comment by wetneb** [comment]
You could increase the number of pages linked in the "Recent posts" sidebar to 20, for instance

**Comment by Sanga-Pal** [comment]
Okay.

**Comment by Sanga-Pal** [comment]
Hey! Actually, I accidentally pushed the changes for this issue in the last branch I was working on, which was for removing the links of SO and Gitter, and since you merged the changes, this issue was also solved thereby. PR #198

**Comment by wetneb** [comment]
Ah great, two birds with one stone :)
