### ISSUE TITLE
Remove link to StackOverflow in the Community page

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/openrefine.org#195]
The Community page features a link to the #openrefine tag on StackOverflow:
https://openrefine.org/community

While some GREL/Jython related questions might be in scope (as programming questions) on StackOverflow, most OpenRefine support questions are not. So I would say we should not display this link that prominently.

**Comment by tfmorris** [comment]
Yes, the current unqualified referral is definitely wrong. I've seen two SO questions about OpenRefine closed in the last few days. 

It might be worth reconsidering the Gitter link as well since newcomers who are directed there end up in an echo chamber mostly by themselves.

**Comment by thadguidry** [comment]
I no longer have the time to actively monitor Gitter.  Agree we should encourage the forums.  We might update the topic header in the Gitter to mention we don't actively monitor it... hmm, if that's the case, we should probably kill it, but I know it has it's uses during Outreachy/GSoC.  Up to ya'll.

**Comment by Sanga-Pal** [comment]
Hi! I would like to work on this issue. So, should we remove both the SO and Gitter links or only the StackOverflow link itself?

**Comment by Sanga-Pal** [comment]
Okay.

**Comment by Sanga-Pal** [comment]
Hi @wetneb , I have created one pull request to fix this issue, looking forward for your reviews on the PR.
