### ISSUE TITLE
Size of openrefine is magic logo is not appropriate in mobile mode.

### ISSUE THREAD

**Issue by parmishh** [OpenRefine/openrefine.org#207]
Size of openrefine is magic logo is not appropriate in mobile mode. at https://openrefine.org/community
I would like to work on it please assign me.

### Expected Behavior
size should be appropriate in mobile view also text should be properly aligned.

### Screenshots

<img width="771" alt="openrefine" src="https://user-images.githubusercontent.com/91942072/227737559-8bc7628e-feb0-4717-8b80-15390d7b4b4e.PNG">

**Comment by wetneb** [comment]
Thanks a lot for reporting and volunteering! I have transferred the issue to the repository which generates the website. It would be great to solve it!

**Comment by parmishh** [comment]
@wetneb How about this, any suggestions or should I make a PR?


https://user-images.githubusercontent.com/91942072/227775957-df86c323-8de3-4f38-b4f6-0bd3f6e2ebaf.mp4

**Comment by wetneb** [comment]
@parmishh it looks perfect to me, looking forward to your PR!

**Comment by wetneb** [comment]
Closed by #208.
