### ISSUE TITLE
Re-structure the guide for new contributors by splitting it into separate pages

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/openrefine.org#232]
The [Contributing](https://openrefine.org/docs/technical-reference/contributing) page in our documentation serves as entry point for new contributors. It has grown a bit wild as we have added information to it, in a rather ad-hoc way.

We should split it in different pages for each type of contributor, so that prospective contributors do not get lost in an ocean of instructions, most of which are irrelevant to them. I would make a page for:
* developers
* designers
* translators
* documentation contributors
* maybe also for user support and issue reporting?

Beyond splitting the existing content into those separate pages, I think we can improve the content itself, but we can do that in a second step.

This is a follow-up on a discussion with @magdmartin

**Comment by tfmorris** [comment]
I'd suggest ordering your list by popularity. The largest potential class of contributors is the users, who can contribute by promoting the product, providing peer support, improving documentation, contributing money, adding/improving translations.

**Comment by wetneb** [comment]
Would you collect all those ways of contributing in one category? To me they are quite different, for instance it's worth having distinct pages for translating and improving documentation.
So far the pages I have created (in #233) are just splitting the existing content, but I have no problem with re-ordering them.

**Comment by tfmorris** [comment]
I guess I think of things more in terms of types of contributors than in types of tasks, but my main point was that the biggest category of potential contributors, normal users, doesn't seem to be addressed at all. You don't need to be able to drive git to contribute.

Perhaps something like this structure where tasks are duplicated as many times as appropriate for each different type of user.

* users - promote OpenRefine, add or improve a translation in your native language, improve documentation, add your favorite recipe to the cookbook, verify and triage new bug reports
* writers - copy edit web site & documentation, add/improve documentation (links issue tag xxx)
* trainers - share your favorite training materials, update Library Carpentry lessons with latest OpenRefine features
* designers - ...
* developers - ...
*

**Comment by magdmartin** [comment]
I think this is a great first step in reorganizing the contribution pages. I'm totally fine with merging it as it is and then continuing to improve it moving forward. 
 
I also agree with @tfmorris  suggestion to structure the contribution by user type. In addition to this PR, I think we should also create explicit contributor pathways and maybe even develop a more detailed contributor manual. This is something that I've heard come up frequently in my interviews.
