### ISSUE TITLE
Problems with the new structure of the contributing documentation

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/openrefine.org#250]
Here are a couple of problems with the new structure of the documentation:

* The "Why get involved" page is contained in a category which has only one page:
![image](https://github.com/OpenRefine/openrefine.org/assets/309908/7d7aecba-c9f6-4a30-a43c-1475be162a71)
This category is unnecessary

* The existing contributing documentation was requalified wholesale as developer documentation, while the "Getting started" page it contains was actually addressing all contributors. This page should rather be moved out of this category.
![image](https://github.com/OpenRefine/openrefine.org/assets/309908/d75c95d7-62cf-4edc-9403-a607dc758573)

* Similarly, the page about documentation contributions is classified inside the "Contributing as a developer" category:
![image](https://github.com/OpenRefine/openrefine.org/assets/309908/5e698a59-aa1d-4014-b728-258d8bfa288d)

* The categories of the Design section have inconsistent capitalization with other pages and category names:
![image](https://github.com/OpenRefine/openrefine.org/assets/309908/fd04458a-41f0-44d8-bc08-97b91fbf1c74)

**Comment by Lydiaofficial** [comment]
I would like to go ahead and fix these issues immediately but have no idea how to make a standalone page in the sidebar.js file after moving such item out of a category.

**Comment by wetneb** [comment]
Amazing! Here is how you can remove the spurious category: #252. You can integrate that in your own PR if you like, or leave it to that one.

**Comment by wetneb** [comment]
Closed by #251
