### ISSUE TITLE
Migrate to Docusaurus 3.0

### ISSUE THREAD

**Issue by thadguidry** [OpenRefine/openrefine.org#274]
Older versions of Docusaurus will not receive security updates after Jan 31, 2024.
Also, there are many new improvements, here's a few:

* MDX v3
* CommonMark
* Mermaid Mindmap and Quadrant charting
* Debug build
* etc.

and fixes, as well as some breaking changes, but I don't expect us to have hardly any breaking changes.

Press Release:  https://docusaurus.io/blog/releases/3.0

**Comment by aakash-a-dev** [comment]
I went through the documentation, and did a check just 5 more pages remaining to rectified then will be able to see the updated packages in action.

Errors remaining are
[ERROR] 5/114 MDX files couldn't compile!
---
Error while compiling file docs/manual/grelfunctions.md (Line=319 Column=15)
Details: Could not parse expression with acorn
---
Error while compiling file docs/manual/wikibase/configuration.md
Details: These MDX global variables do not seem to be available in scope: batch_id lang version
---
Error while compiling file docs/technical-reference/migrating-older-extensions.md
Details: These MDX global variables do not seem to be available in scope: basedir
---
Error while compiling file docs/technical-reference/openrefine-api.md (Line=198 Column=49)
Details: Could not parse expression with acorn
---
Error while compiling file static/img/2022survey/2022-survey-openanswers.md (Line=544 Column=3)
Details: Expected a closing tag for `<cheeky>` (544:423-544:436) before the end of `paragraph`
