### ISSUE TITLE
Advertise the 2024 user survey

### ISSUE THREAD

**Issue by magdmartin** [OpenRefine/openrefine.org#358]
I am finalizing the [2024 user survey](https://forum.openrefine.org/t/drafting-the-2024-user-survey/1431/23?u=martin) and would like to discuss how we will advertise it to reach as many users as possible. From this [initial discussion](https://forum.openrefine.org/t/results-of-two-user-surveys-for-wikimedia-commons-users-of-openrefine/1111/14?u=martin), I would like to advertise it via the following channel:

- [ ] Create a notification in OpenRefine (thanks to https://github.com/OpenRefine/OpenRefine/issues/6290)
- [ ] Add a button on the homepage openrefine.org,
- [x] Create a pinned issue in OpenRefine/OpenRefine Github repo
- [x] Create a pinned message on the forum
- [x] Publish messages on social media (e.g., LinkedIn, Mastodon). I suggest posting three messages: one at the start of the survey (early August), another at mid-term (early September), and a reminder one week before it closes (end of September or early October).
- [ ] Personal email outreach to trainers, advocates, and other community members, inviting them to share within their community.
- [ ] Post in various community forums that we are aware of (Slack, Telegram, forums...). I can compile and share a list later on.

This issue is to validate the distribution channels and link the different PR to update the OpenRefine/openrefine.org repo. You can still comment on the survey design [the forum.](https://forum.openrefine.org/t/drafting-the-2024-user-survey/1431/23?u=martin)

**Comment by thadguidry** [comment]
I think all of those channels and any more would be fine, since the goal is to reach as many OpenRefine users as possible.  Perhaps also within Library and News channels, oh wait, you mention inviting them to share within their community (I guess so we don't have to...makes sense)

**Comment by magdmartin** [comment]
>Perhaps also within Library and News channels, oh wait, you mention inviting them to share within their community (I guess so we don't have to...makes sense)

@thadguidry  I plan to do both
