### ISSUE TITLE
Improve Post Download thank you page

### ISSUE THREAD

**Issue by magdmartin** [OpenRefine/openrefine.org#371]
This issue follows the Heuristic Analysis done by [asengupta](https://forum.openrefine.org/u/asengupta) on [the forum](https://forum.openrefine.org/t/conducting-a-ux-audit/1694/10?u=martin)

The proposition is to update the next step on the  post-download thank you page for [linux](https://openrefine.org/post_download?version=3.8.2&platform=linux), [macOs](https://openrefine.org/post_download?version=3.8.2&platform=mac) and [windows with java](https://openrefine.org/post_download?version=3.8.2&platform=win-with-java) to
* add a link to the documentation and relevant tutorials 
* make the instructions for the installation process more granular with numbered steps or screenshots. See the [macOs installation heuristic](https://www.figma.com/board/UvWNdZ5c4RvzxZioJ8YFXe/OpenRefine-User-Flows?node-id=2-2040&node-type=section) and process to circumvent macOS security warning. Those can be linked to specific documentation pages. 
* remove the mention of the financial donation. It does not make sense to ask for financial support to first time user 
* Reframe the community with an emphasis on support

**Comment by magdmartin** [comment]
For the macOS download page make the warning about _how to circumvent the security warning_ more prominent

**Comment by ViragJain3010** [comment]
is this issue still up? If so I would like to work on this.

**Comment by magdmartin** [comment]
@ViragJain3010  please go ahead
