### ISSUE TITLE
Latest release not available on the download page

### ISSUE THREAD

**Issue by Abbe98** [OpenRefine/openrefine.org#408]
https://openrefine.org/download lists 3.8.6 as the latest while the latest version is 3.8.7. 3.8.6 also appears to be broken according to users.

**Comment by mynk2611** [comment]
i think version updates are also not on whats_new page?

> https://openrefine.org/download lists 3.8.6 as the latest while the latest version is 3.8.7. 3.8.6 also appears to be broken according to users.

**Comment by magdmartin** [comment]
@mynk2611 good catch, let me update my PR

**Comment by tfmorris** [comment]
That's my bad. I forgot to update releases.json when I respun the 3.8.6 release.
