### ISSUE TITLE
Update Support/Sponsors and make it a list

### ISSUE THREAD

**Issue by thadguidry** [OpenRefine/openrefine.org#54]
We should make a separate div list element with logos and dates next to each for our sponsors.
Or just have a Sponsors page separately...dunno...

Something like this for now...

Sponsors:
- 2020 Chan Zuckerberg Initiative
- 2018 Google News Initiative

**Comment by BhaswatiRoy** [comment]
Hello @thadguidry 
We can probably add the list of sponsors to the "donate" page itself.
![image](https://user-images.githubusercontent.com/78029145/214067321-8d71502e-7b78-45a9-9b20-ce9c2591077d.png)
I can work on this!

**Comment by amyra98** [comment]
Can I work on this issue @thadguidry Is there any section on sponsors where I have to add this or create new section for either please specify the location

**Comment by thadguidry** [comment]
@amyra98 Since @wetneb has changed our web pages layout, I would refer to him for questions.  This might also tie into a bit of our updated governance needs as well. This issue was originally thought of as a simple *thank you* to our sponsors and to let others know where OpenRefine has received large financial support through sponsorship that directly lead to some major features and benefits to our users.  This issue itself is entirely optional, but a nice thing to do in the open source world oftentimes.  We might look to other open source communities to glean insight on how they do this.  Inkscape, Godot, etc.

**Comment by wetneb** [comment]
I think this issue is generally not suitable for newcomers as it requires them to write new content, which means having a good overview of OpenRefine's past funding history and projects.

**Comment by thadguidry** [comment]
@martinrefinepro Since we're discussing larger changes and you'll likely handle those.  Shall I close this issue then?

**Comment by magdmartin** [comment]
Yes I believe the we can close this issue. The list of sponsor is already available on the [funding page](https://openrefine.org/funding)
